# propagation error

การสร้างฟังชันควร มี retrun error อยู่ด้วยเสมอ เพื่อจะได้รู้ว่าจุดไหนที่มีปัญหา
func getBalance() (int, error) {}

balance, err := getBalance()
...........................

const dbReady = false
var balance = 201

func main() {

log.SetFlags(log.Ltime)
transection, err := withdraw(200)
if err != nil {
log.Fatal("main:", err)
}
fmt.Println(`success`, transection)
}

func withdraw(amount int) (int, error) {
balance, err := getBalance()
if err != nil {
return 0, fmt.Errorf("withdra : %v", err)
}

if amount > balance {
return 0, errors.New(" withdraw : insufficient fund")
}
return amount, nil
}

func getBalance() (int, error) {

if !dbReady {
return 0, errors.New("getBalance : database is down")
}
return balance, nil
}
